In [9]:
import numpy as np

# Defining the sigmoid function for activations
def sigmoid(x):
    return 1/(1+np.exp(-x))

# Derivative of the sigmoid function
def sigmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Input data
x = np.array([0.1, 0.3])
# Target
y = 0.2
# Input to output weights
weights = np.array([-0.8, 0.5])

# The learning rate, eta in the weight step equation
learnrate = 0.5

# Total learning cycles

epochs = 20

# results
results = []

for _ in range(epochs):
    # the linear combination performed by the node (h in f(h) and f'(h))
    h = x[0]*weights[0] + x[1]*weights[1]
    # or h = np.dot(x, weights)

    # The neural network output (y-hat)
    nn_output = sigmoid(h)

    # output error (y - y-hat)
    error = y - nn_output

    # output gradient (f'(h))
    output_grad = sigmoid_prime(h)

    # error term (lowercase delta)
    error_term = error * output_grad

    # Gradient descent step 
    del_w = [ learnrate * error_term * x[0],
              learnrate * error_term * x[1]]
    # or del_w = learnrate * error_term * x

    # Update weights
    weights = weights - del_w
    
    results.append((h, np.dot(x, weights)))

print("First Cycle")
print(f"Old prediction: {results[0][0]} vs actual: {y}")
print(f"New prediction: {results[0][1]} vs actual: {y}\n")

print("Last Cycle")
print(f"Old prediction: {results[-1][0]} vs actual: {y}")
print(f"New prediction: {results[-1][1]} vs actual: {y}\n")

First Cycle
Old prediction: 0.06999999999999998 vs actual: 0.2
New prediction: 0.07396380307900689 vs actual: 0.2

Last Cycle
Old prediction: 0.14732372894752788 vs actual: 0.2
New prediction: 0.15151052573416032 vs actual: 0.2



In [17]:
%reset

# Calculating gradient quiz
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    """
    # Derivative of the sigmoid function
    """
    return sigmoid(x) * (1 - sigmoid(x))

learnrate = 0.5

x = np.array([1, 2, 3, 4])

y = np.array(0.5)

# Initial weights
w = np.array([0.5, -0.5, 0.3, 0.1])

## Calculate one gradient descent step for each weight
## Note: Some steps have been consolidated, so there are
## fewer variable names than in the above sample code

# TODO: Calculate the node's linear combination of inputs and weights
h = x @ w

# TODO: Calculate output of neural network
nn_output = sigmoid(h)

# TODO: Calculate error of neural network
error = y - nn_output

# TODO: Calculate the error term
#       Remember, this requires the output gradient, which we haven't
#       specifically added a variable for.
error_term = error * sigmoid_prime(h)

# # TODO: Calculate change in weights
del_w = learnrate * error_term * x

print('Neural Network output:')
print(nn_output)
print('Amount of Error:')
print(error)
print('Change in Weights:')
print(del_w)

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


Neural Network output:
0.6899744811276125
Amount of Error:
-0.1899744811276125
Change in Weights:
[-0.02031869 -0.04063738 -0.06095608 -0.08127477]


In [27]:
%reset

import numpy as np
import pandas as pd

admissions = pd.read_csv('data/student_admission.csv')

# Make dummy variables for rank
data = pd.concat([admissions, pd.get_dummies(admissions['rank'], prefix='rank')], axis=1)
data = data.drop('rank', axis=1)

# Standarize features
for field in ['gre', 'gpa']:
    mean, std = data[field].mean(), data[field].std()
    data.loc[:,field] = (data[field]-mean)/std
    
# Split off random 10% of the data for testing
np.random.seed(42)
sample = np.random.choice(data.index, size=int(len(data)*0.9), replace=False)
data, test_data = data.iloc[sample], data.drop(sample)

# Split into features and targets
features, targets = data.drop('admit', axis=1), data['admit']
features_test, targets_test = test_data.drop('admit', axis=1), test_data['admit']

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

# TODO: We haven't provided the sigmoid_prime function like we did in
#       the previous lesson to encourage you to come up with a more
#       efficient solution. If you need a hint, check out the comments
#       in solution.py from the previous lecture.

# Use to same seed to make debugging easier
np.random.seed(42)

n_records, n_features = features.shape
last_loss = None

# Initialize weights
weights = np.random.normal(scale=1 / n_features**.5, size=n_features)

# Neural Network hyperparameters
epochs = 1000
learnrate = 0.5

for e in range(epochs):
    del_w = np.zeros(weights.shape)
    for x, y in zip(features.values, targets):
        # Loop through all records, x is the input, y is the target

        # Note: We haven't included the h variable from the previous
        #       lesson. You can add it if you want, or you can calculate
        #       the h together with the output

        # TODO: Calculate the output
        output = sigmoid(np.dot(x, weights))

        # TODO: Calculate the error
        error = y - output

        # TODO: Calculate the error term
        error_term = error * output * (1 - output)

        # TODO: Calculate the change in weights for this sample
        #       and add it to the total weight change
        del_w += error_term * x

    # TODO: Update weights using the learning rate and the average change in weights
    weights += learnrate * del_w / n_records

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        out = sigmoid(np.dot(features, weights))
        loss = np.mean((out - targets) ** 2)
        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss


# Calculate accuracy on test data
tes_out = sigmoid(np.dot(features_test, weights))
predictions = tes_out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


Train loss:  0.2627609384996635
Train loss:  0.20928619409324875
Train loss:  0.20084292908073426
Train loss:  0.19862156475527873
Train loss:  0.1977985139668603
Train loss:  0.19742577912189863
Train loss:  0.1972350774624106
Train loss:  0.1971294562509248
Train loss:  0.19706766341315082
Train loss:  0.19703005801777368
Prediction accuracy: 0.725


In [41]:
# random practice
import numpy as np

l = np.array([ 0.49671415, -0.1382643 ,  0.64768854])

print(l.T, '\n', l[:, None])

[ 0.49671415 -0.1382643   0.64768854] 
 [[ 0.49671415]
 [-0.1382643 ]
 [ 0.64768854]]


In [47]:
%reset

'''
Quiz: Program a forward pass on 4 input layers, 3 hidden layers and 2 output layers.
'''

import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)

# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))

weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


# TODO: Make a forward pass through the network

hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


[0.41492192 0.42604313 0.5002434 ]
Hidden-layer Output:
[0.41492192 0.42604313 0.5002434 ]
Output-layer Output:
[0.51549741 0.5078162 ]


In [80]:
%reset

'''
Rate of change in weight is as follows

Δw = ηδx

Where

Δw = delta of w change in weight
η = Ada or learning rate
δ = delta or error term.
x = input to the system
'''

# Simple back propagation.
import numpy as np


input_layer = np.array([0.1, 0.3])
input_weights = np.array([0.4, -0.2])

hidden_weight = 0.1

y = 1

learning_rate = 0.5

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Forward pass.
h_j = input_layer @ input_weights

hidden_layer_activation = sigmoid(h_j)

output_layer_activation = sigmoid( hidden_layer_activation * hidden_weight )

# Backward propagation

# Output to hidden layer
output_layer_error = y - output_layer_activation

output_error_term_delta = output_layer_error * output_layer_activation * (1 - output_layer_activation)

change_in_weight_from_output_to_hidden = learning_rate * output_error_term_delta * output_layer_activation

# hidden to input
'''
The reason we do hidden_weight * output_error_term_delta instead of something like we did above like output_layer_error
is we don't have it in the hidden layers. But we do know that the contribution of each neuron will be proportional to how much
their weight is so * the output error delta by the weight will appropriately distribute/propgate/backpropagate the output error in the 
layers.
'''
hidde_layer_error = hidden_weight * output_error_term_delta

hidden_error_term_delta = hidde_layer_error * hidden_layer_activation * (1 - hidden_layer_activation)

change_in_weights_from_hidden_to_input = [ learning_rate * hidden_error_term_delta * input_layer[0], learning_rate * hidden_error_term_delta * input_layer[1] ]

# Results
change_in_weight_from_output_to_hidden, change_in_weights_from_hidden_to_input

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


(0.031211742163735474, [0.00015227506618662777, 0.0004568251985598832])

In [83]:
%reset

'''
Quiz exercise. Code the backward pass.
'''

import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)

# TODO: Calculate error term for hidden layer
hidden_error_term = output_error_term * weights_hidden_output * hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)


Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]
Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]


In [91]:
'''
Quiz: Implement backpropagation on the student admission exercise.
'''

%reset

import numpy as np
import pandas as pd

admissions = pd.read_csv('data/student_admission.csv')

# Make dummy variables for rank
data = pd.concat([admissions, pd.get_dummies(admissions['rank'], prefix='rank')], axis=1)
data = data.drop('rank', axis=1)

# Standarize features
for field in ['gre', 'gpa']:
    mean, std = data[field].mean(), data[field].std()
    data.loc[:,field] = (data[field]-mean)/std
    
# Split off random 10% of the data for testing
np.random.seed(42)
sample = np.random.choice(data.index, size=int(len(data)*0.9), replace=False)
data, test_data = data.iloc[sample], data.drop(sample)

# Split into features and targets
features, targets = data.drop('admit', axis=1), data['admit']
features_test, targets_test = test_data.drop('admit', axis=1), test_data['admit']

np.random.seed(21)

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


# Hyperparameters
n_hidden = 2  # number of hidden units
epochs = 900
learnrate = 0.005

n_records, n_features = features.shape
last_loss = None
# Initialize weights
weights_input_hidden = np.random.normal(scale=1 / n_features ** .5,
                                        size=(n_features, n_hidden))
weights_hidden_output = np.random.normal(scale=1 / n_features ** .5,
                                         size=n_hidden)

for e in range(epochs):
    del_w_input_hidden = np.zeros(weights_input_hidden.shape)
    del_w_hidden_output = np.zeros(weights_hidden_output.shape)
    for x, y in zip(features.values, targets):
        ## Forward pass ##
        # TODO: Calculate the output
        hidden_input = np.dot(x, weights_input_hidden)
        hidden_output = sigmoid(hidden_input)

        output = sigmoid(np.dot( hidden_output, weights_hidden_output ))

        ## Backward pass ##
        # TODO: Calculate the network's prediction error
        error = y - output

        # TODO: Calculate error term for the output unit
        output_error_term = error * output * (1 - output)

        ## propagate errors to hidden layer

        # TODO: Calculate the hidden layer's contribution to the error
        hidden_error = output_error_term * weights_hidden_output
        
        # TODO: Calculate the error term for the hidden layer
        hidden_error_term = hidden_error * hidden_output * (1 - hidden_output)
        
        # TODO: Update the change in weights
        del_w_hidden_output += output_error_term * hidden_output
        del_w_input_hidden += hidden_error_term * x[:, None]

    # TODO: Update weights  (don't forget to division by n_records or number of samples)
    weights_input_hidden += learnrate * del_w_input_hidden / n_records
    weights_hidden_output += learnrate * del_w_hidden_output / n_records

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        hidden_output = sigmoid(np.dot(x, weights_input_hidden))
        out = sigmoid(np.dot(hidden_output,
                             weights_hidden_output))
        loss = np.mean((out - targets) ** 2)

        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss

# Calculate accuracy on test data
hidden = sigmoid(np.dot(features_test, weights_input_hidden))
out = sigmoid(np.dot(hidden, weights_hidden_output))
predictions = out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


Train loss:  0.2763000206585236
Train loss:  0.27487280940102565
Train loss:  0.27348146900538234
Train loss:  0.2721253511981268
Train loss:  0.2708037972995826
Train loss:  0.2695161402601932
Train loss:  0.2682617065761968
Train loss:  0.26703981808591787
Train loss:  0.26584979364857986
Train loss:  0.26469095070807314
Prediction accuracy: 0.425
